### ISSUE TITLE
ngx_openidc_module.so version 1016001 instead of 1021000

### ISSUE THREAD

**Issue by wongkeewee** [zmartzone/ngx_openidc_module#11]
Hi,

I am trying to implement the ngx_openid_module into Nginx Reverse Proxy.

I've managed to install all the dependencies (jansson, libmemcache, cjose, liboauth2, etc) and installed the ngx_openid_module rpm.  However during startup, nginx is complaining about the module version  
`nginx: [emerg] module "/usr/lib64/nginx/modules/ngx_openidc_module.so" version 1016001 instead of 1021000 in /etc/nginx/nginx.conf:8`  

I've tried to recompile the module following the steps [here](https://www.nginx.com/blog/failed-nginx-plus-upgrade-module-version-x-instead-of-y/) but it seems like the git do not have the config file for recompiling.  

Any idea how can I solve the version issue?

The nginx I have is
```
# nginx -v
nginx version: nginx/1.21.0
```

**Comment by zandbelt** [comment]
what distribution are you on?

**Comment by wongkeewee** [comment]
I'm running the RP on RHEL7

**Comment by zandbelt** [comment]
it seems you're not running the stock NGINX version 1.16.0 then

**Comment by wongkeewee** [comment]
The Nginx package were installed using Yum

So to use this module, we'll need to stick with v1.16.0?

**Comment by zandbelt** [comment]
ok, I see that the stock NGINX version has been updated in the mean time; I'll update the RPM shortly; you'll have to compile from scratch in the mean time

**Comment by zandbelt** [comment]
I'm getting 1.20.1 now... https://centos.pkgs.org/7/epel-x86_64/nginx-1.20.1-2.el7.x86_64.rpm.html

**Comment by wongkeewee** [comment]
I tried recompiling following [this](https://www.nginx.com/blog/failed-nginx-plus-upgrade-module-version-x-instead-of-y/)

But the git repo is missing the config file, how else can I compile the module?

**Comment by wongkeewee** [comment]
Hi @zandbelt, are you able to advise on how to compile the module from github?

**Comment by zandbelt** [comment]
use `./autogen.sh` first
