### ISSUE TITLE
How to build? Use in a docker container?

### ISSUE THREAD

**Issue by dimaqq** [zmartzone/ngx_openidc_module#2]
I'd love to test this module against our custom OIDC server (IDP).

I wish there were instructions for someone who's not familiar with nginx, on how to "add" the module to the server, how to build it, how to add it into a container.

For now I'll try to follow https://gist.github.com/hermanbanken/96f0ff298c162a522ddbba44cad31081 and I'll post here if that works or what I figure out.

**Comment by dimaqq** [comment]
It turns out that build expects to find `ngx_openidc_module-3.1.0/config` which is not in the tarball.
I guess I'll just test out the `.deb` or `.rpm` instead.

**Comment by zandbelt** [comment]
please use the provided packages indeed
