### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by fostermi** [zmartzone/ngx_openidc_module#8]
I don't see much activity here and one of the open issues has a comment that this is "beta". Is this project still being developed? I'd rather use this than the lua module which needs something like openresty. We use the mod_auth_openidc module for Apache extensively and would like an nginx variant.

**Comment by zandbelt** [comment]
It is no longer beta since last December, it is fully functional (although basic) but not used that much by others yet. I'd be interested in your feedback. See also: https://hanszandbelt.wordpress.com/2020/12/22/mvp-oauth-2-x-openid-connect-modules-for-nginx-and-apache/

**Comment by fostermi** [comment]
Ok, great. Would it be possible to create a new artifact for debian-buster? The official Docker images for nginx use this as their default installation and the version of nginx in Bionic is somewhat dated (v1.14.0). However trying to install liboauth2 with buster is problematic because of the dependency of libhiredis0.13, which doesn't exist in Buster  (libhiredis0.14 is the new library). Also, nginx-core doesn't exist in Buster. A new artifact for Ubuntu Focal with nginx-core would also be fine with an updated dependency libhiredis0.14 as that has nginx-core, it would just mean creating a custom Docker image for nginx.

**Comment by zandbelt** [comment]
I have added Debian Buster and Ubuntu Focal packages to https://github.com/zmartzone/ngx_openidc_module/releases/tag/v3.2.0
